services:
  portainer:
    image: portainer/portainer-ce:${PORTAINER_TAG}
    container_name: portainer
    hostname: portainer
    restart: unless-stopped
    # ports:
    #   - "9000:9000"
    #   - "9443:9443"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - ./data:/data
    networks:
      - control-plane

    labels:
      - traefik.enable=true
      - traefik.http.routers.portainer.rule=Host(`portainer.${APP_DOMAIN}`)
      - traefik.http.routers.portainer.entrypoints=websecure
      - traefik.http.routers.portainer.tls.certresolver=myresolver
      - traefik.http.services.portainer.loadbalancer.server.port=9000

networks:
  control-plane:
    external: true
