services:
  whatsupdocker:
    image: getwud/wud:${WUD_TAG}
    container_name: wud
    hostname: wud
    restart: unless-stopped
    # ports:
    #   - 3000:3000
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - WUD_REGISTRY_CUSTOM_N8N_URL=https://docker.n8n.io
      - WUD_TRIGGER_SLACK_SUPPORT_TOKEN=${WUD_TRIGGER_SLACK_SUPPORT_TOKEN}
      - WUD_TRIGGER_SLACK_SUPPORT_CHANNEL=${WUD_TRIGGER_SLACK_SUPPORT_CHANNEL}
      - WUD_TRIGGER_SLACK_SUPPORT_THRESHOLD=${WUD_TRIGGER_SLACK_SUPPORT_THRESHOLD}
    networks:
      - control-plane
    labels:
      - traefik.enable=true
      - traefik.http.routers.wud.rule=Host(`wud.${APP_DOMAIN}`)
      - traefik.http.routers.wud.entrypoints=websecure
      - traefik.http.routers.wud.tls.certresolver=myresolver
      - traefik.http.services.wud.loadbalancer.server.port=3000
      - traefik.http.routers.wud.middlewares=auth

networks:
  control-plane:
    external: true
